runtime: nodejs20

handlers:
  # 规则 1: 将所有请求首先尝试映射到 dist 目录下的静态文件。
  # 例如，对 /assets/index.js 的请求会提供 dist/assets/index.js 文件。
  # 对 /desktop_pc/scene-transformed.glb 的请求会提供 dist/desktop_pc/scene-transformed.glb 文件。
  # 这一个规则就处理了所有 js, css, glb, png, woff 等静态资源。
  - url: /
    static_dir: dist

  # 规则 2: 如果上面的规则在 dist 目录中找不到匹配的文件（例如，对于 /contact 或 /works 这样的前端路由），
  # 则将请求回退到 index.html。这使得 React Router 能够接管路由。
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html